// <auto-generated />
namespace CMS_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModTbl_Pin_ModCol_Domain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModTbl_Pin_ModCol_Domain));
        
        string IMigrationMetadata.Id
        {
            get { return "201807040928302_ModTbl_Pin_ModCol_Domain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
